name: Scan Helm Charts
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: helm-charts/
          framework: helm kubernetes secrets
          skip_check: CKV_K8S_21 
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
