apiVersion: dp.wso2.com/v1alpha1
kind: BackendJWT
metadata:
  name: backend-jwt-policy
spec:
  encoding: "Base64"
  signingAlgorithm: "SHA256withRSA"
  header: "X-JWT-Assertion"
  tokenTTL: 3600
  customClaims:
    - claim: "admin"
      value: "http://wso2.org/claims/enduser"
    - claim: "test"
      value: "1"
      type: float