kubeProxyReplacement: true
k8sServiceHost: kind-control-plane # use master node in kind network
k8sServicePort: 6443 # use api server port
hostServices:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
envoyConfig:
  enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
hubble:
  relay:
    enabled: true
