apiVersion: dp.wso2.com/v1alpha1
kind: BackendJWT
metadata:
  labels:
    app.kubernetes.io/name: backendjwt
    app.kubernetes.io/instance: backendjwt-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: backendjwt-sample
spec:
  # TODO(user): Add fields here
