apiVersion: dp.wso2.com/v1alpha2
kind: APIPolicy
metadata:
  labels:
    app.kubernetes.io/name: apipolicy
    app.kubernetes.io/instance: apipolicy-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: apipolicy-sample
spec:
  override:
    subscriptionValidation: true
  targetRef:
    group: dp.wso2.com
    kind: API
    name: 5be9683b59c60816f0d6bf8debbc8f59610810df
