apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: echo-api
spec:
  apiName: Echo API
  organization: apk-system
  apiType: REST
  apiVersion: 1.0.0
  basePath: /echo-api/1.0.0
  production:
    - httpRouteRefs:
        - prod-http-route-echo-api

---

apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: details-api
spec:
  apiName: Details API
  organization: apk-system
  apiType: REST
  apiVersion: 1.0.0
  basePath: /details-api/1.0.0
  production:
    - httpRouteRefs:
        - prod-http-route-details-api