apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: ebpf-daemonset
  template:
    metadata:
      labels:
        name: ebpf-daemonset
    spec:
      containers:
        - name: ebpf-daemonset
          image: sniffer:1.0
          # imagePullPolicy: IfNotPresent # add this line
          securityContext:
            privileged: true
            capabilities:
              add:
                - CAP_SYS_ADMIN
                - CAP_SYS_MODULE
          volumeMounts:
            - name: libmodules
              mountPath: /lib/modules
            - name: usr-src
              mountPath: /usr/src
            # - name: linux-kernel
            #   mountPath: /linux-kernel
            - name: sys
              mountPath: /sys
      volumes:
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: usr-src
          hostPath:
            path: /usr/src
            type: Directory
        # - name: linux-kernel
        #   hostPath:
        #     path: /linux-kernel
        #     type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
